token: "TokenTimeIsBackBuddyss"  # Lichess OAuth2 Token.

engines:
  standard:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-bmi2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 14.8
    uci_options:
      Threads: 4 #hg
      Hash: 4096
      Move Overhead: 134
    limits:
      # time: 20.0
      # depth: 50
      # nodes: 8000000

  variants:
    dir: "./engines"
    name: "fairy-stockfish_x86-64-bmi2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 4
      Hash: 3456
      Move Overhead: 240
      Use NNUE: true 
      EvalFile: "horde-28173ddccabe.nnue:racingkings-636b95f085e3.nnue:crazyhouse-8ebf84784ad2.nnue:kingofthehill-978b86d0e6a4.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:3check-cb5f517c228b.nnue"
    limits:
     # time: 20.0
      #depth: 50
    #  nodes: 5000000
  0.5+0:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-bmi2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 5.0
    uci_options:
      Threads: 4
      Hash: 4096
      Move Overhead: 200
     # Use NNUE: true 
    #  EvalFile: "nn-46832cfbead3.nnue"
    limits:
     # time: 20.0
      #depth: 50
    #  nodes: 5000000
  standard_human:
    dir: "./engines"
    name: "stockfish-7-x64-bmi2"
    ponder: false
    silence_stderr: false
    move_overhead_multiplier: 6.9
    uci_options:
      Threads: 4
      Hash: 269
      Move Overhead: 125
    limits:

  bullet:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-bmi2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 15.55
    uci_options:
       Threads: 4
       Hash: 2256
       Move Overhead: 120
    limits: 
    
  chess960:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-bmi2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 5.8
    uci_options:
       Threads: 4
       Hash: 4096
       Move Overhead: 169
    limits: 


syzygy:
  standard:
    enabled: true
    paths:
      - "./engines/syzygy"
    max_pieces: 6
    instant_play: true
  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 400
  books:
    standard_white:
      selection: best_move 
      allow_repetitions: true   
     # max_depth: 80
      names:
      #  - ai 
        - lilawhite
      #  - one
        - Perfect2023
        - Opimus3.1
        - optimus2502
       # - optimus4
      #  - Opimus3.1
        - noob
    standard_black:
      selection: best_move 
      allow_repetitions: true   
     # max depth : 45 
      names:
        - niki
      #  - optimus4
        - lilablack
     #   - Titans
        - Opimus3.1
       # - optimus4
    standard_human: 
      selection: best_move 
      allow_repetitions: true   
      names: 
        - gm
        - noob
        - Titans
    standard_black_tournament:
      selection: best_move
      allow_repetitions: true   
      names:
        - drawing
        - niki 
        - one    
        - badbot 
        - Opimus3.1
    standard_white_tournament:
      selection: best_move
      allow_repetitions: true   
      names: 
        - drawingforwhite
        - niki
        - one 
        - Opimus3.1
    0.5+0_black:
      selection: best_move
      allow_repetitions: true   
      names: 
        - winwhite
        - niki
        - Opimus3.1
    antichess_black:
      selection: best_move
      allow_repetitions: true   
      names: 
        - anti
    horde_white:
      selection: best_move
      allow_repetitions: true   
      names: 
        - horde
    horde_black:
      selection: best_move
      allow_repetitions: true   
      names:
        - fghhorde
    chess960:
      selection: best_move
      allow_repetitions: true 
      names:
        - chess960 
        - 960
    antichess_white:
      selection: best_move
      allow_repetitions: false
      names:
        - realanti
        - anti
online_moves:
  opening_explorer:
    enabled: false                        # Activate online moves from Lichess opening explorer. The move that has performed best for this bot is played.
    priority: 300                         # Priority with which this move source is used. Higher priority is used first.
#   player: Username                      # Player whose Lichess opening explorer should be used. Comment this to use your own or with anti your opponent's.
    only_without_book: false              # Whether the Lichess opening explorer should only be used if there is no matching book.
    use_for_variants: false               # Whether the Lichess opening explorer should be used for other variants than standard and chess960.
    allow_repetitions: false              # Whether the Lichess opening explorer can create repetitions on the board. Can lead to unintentional draws.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
    min_games: 5                          # Minimum number of games in which the position must have occurred.
    only_with_wins: false                 # Whether to play only moves that have won before.
    selection: "performance"              # Move selection is "performance" or "win_rate".
    anti: false                           # Whether to play the moves in which the opponent performs the worst.
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from Lichess opening explorer. (Comment this line for max moves)
  lichess_cloud:
    enabled: false                        # Activate online moves from Lichess cloud eval.
    priority: 200                         # Priority with which this move source is used. Higher priority is used first.
    only_without_book: false              # Whether the cloud should only be used if there is no matching book.
    use_for_variants: false               # Whether the cloud should be used for other variants than standard and chess960.
    allow_repetitions: false              # Whether the cloud can create repetitions on the board. Can lead to unintentional draws.
    trust_eval: false                     # Whether the cloud eval should be trusted for draw offers and resignations.
    min_eval_depth: 10                    # Minimum evaluation depth.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from Lichess cloud eval. (Comment this line for max moves)
  chessdb:
    enabled: false                        # Activate online moves from https://chessdb.cn/queryc_en/
    priority: 100                         # Priority with which this move source is used. Higher priority is used first.
    only_without_book: false              # Whether the chessdb should only be used if there is no matching book.
    allow_repetitions: false              # Whether the chessdb can create repetitions on the board. Can lead to unintentional draws.
    trust_eval: false                     # Whether the chessdb eval should be trusted for draw offers and resignations.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
    best_move: false                      # Whether only the single best move should be played.
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from chessdb. (Comment this line for max moves)
  online_egtb:
    enabled: false                        # Activate online endgame tablebases from Lichess.
    min_time: 5                           # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 3                            # Time the server has to respond.

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 2
  min_game_length: 30
  against_humans: false
 # min_rating: 3000

resign:
  enabled: true
  score: -1200
  consecutive_moves: 6
  against_humans: false
  min_rating: 3000

challenge:
  concurrency: 1
  bullet_with_increment_only: false
  max_takebacks: 2
  min_initial: 30
  max_initial: 1200
  variants:
    - standard
    - chess960
    - antichess
    - atomic
    - kingOfTheHill
    - racingKings
    - threeCheck
    - fromPosition
    - crazyhouse
    - horde
  time_controls:
    - bullet
    - blitz
    - rapid
  #  - classical
  bot_modes:
   # - casual
    - rated
  human_modes:
    - casual
   #- rated

matchmaking:
  delay: 10
  timeout: 30
  selection: cyclic
  types:
    hp:
      tc: 0.5+0
    bp:
      tc: 0.75+0
    bullet:
      tc: 0+1
      variant: chess960
    bulle2:
      tc: 3+0
    bc:
      tc: 5+0
    bm3:
      tc: 1+0
    gulugulu:
      tc: 0+1
    guliguli:
      tc: 10+0
    hvj:
      tc: 1.5+0
    win:
      tc: 8+0
    loss:
      tc: 2+0
    drum:
      tc: 0.5+0
      variant: chess960
    anti:
      tc: 0.75+0
      variant: antichess
    horde:
      tc: 0.75+0
      variant: horde
    

messages:
  greeting: "Xin Chào! Chúc Bạn Chơi Vui Vẻ!"
  goodbye: "Good bye! Cảm ơn đã chơi!"
  greeting_spectators: "Hello my spectators! My strength is best!"
  goodbye_spectators: "Nice game! I will train and beat you many time!"

whitelist:
  - Supratsa
  - InvinxibleFlxsh
blacklist:
  - NimsiluBot
 # - VEER-OMEGA-BOT
books:
  Titans: "./engines/black.bin"
  optimus2502: "./engines/OPTIMUS2502.bin"
  optimus4: "./engines/win.bin"
  Perfect2023: "./engines/white.bin"
  Opimus3.1: "./engines/Optical.bin"
  noob: "./engines/Titans.bin"
  ai: "./engines/nikibook.bin"
  gm: "./engines/gm2001(1).bin"
  niki: "./engines/nikimoves.bin"
  lilawhite: "./engines/lilawhite.bin"
  lilablack: "./engines/lila.bin"
  winwhite: "./engines/winwhite.bin"
  one: "./engines/book1.bin"
  anti: "./engines/anti_book.bin"
  horde: "./engines/horde_book_white.bin"
  fghhorde: "./engines/horde_book_black.bin"
  drawing: "./engines/drawing.bin"
  drawingforwhite: "./engines/drawingforwhite.bin"
  badbot: "./engines/badwhite.bin"
  chess960: "./engines/chess960.bin"
  960: "./engines/randomchess.bin"
  realanti: "./engines/anti.bin"

